const db = require ('../src/database')

exports.seed = async (knex) => {
    await db('cars').insert([
        { brand: 'Toyota', model: 'Corolla', year: 2018, plate: 'ABC-1D23' },
        { brand: 'Ford', model: 'Fusion', year: 2020, plate: 'XYZ-5G67' },
        { brand: 'Chevrolet', model: 'Cruze', year: 2022, plate: 'QRS-7J89' },
        { brand: 'Hyundai', model: 'Veloster', year: 2021, plate: 'JKL-3A22' },
        { brand: 'Fiat', model: 'Argo', year: 2019, plate: 'OPQ-4B34' },
        { brand: 'Honda', model: 'Civic', year: 2020, plate: 'MNO-9C45' },
        { brand: 'Volkswagen', model: 'Gol', year: 2023, plate: 'DEF-8H56' },
        { brand: 'BMW', model: '320i', year: 2022, plate: 'GHI-6I67' },
        { brand: 'Audi', model: 'A3', year: 2021, plate: 'PQR-2J78' },
        { brand: 'Mercedes', model: 'A-Class', year: 2022, plate: 'STU-1A89' },
        { brand: 'Nissan', model: 'Sentra', year: 2020, plate: 'VWX-3B90' },
        { brand: 'Mazda', model: 'Miata', year: 2022, plate: 'LMN-4C12' },
        { brand: 'Peugeot', model: '208', year: 2021, plate: 'EFG-2D34' },
        { brand: 'Renault', model: 'Kwid', year: 2021, plate: 'JKL-5E45' },
        { brand: 'Fiat', model: 'Mobi', year: 2022, plate: 'ABC-7F56' },
        { brand: 'Chery', model: 'Tiggo', year: 2022, plate: 'TUV-6G67' },
        { brand: 'Honda', model: 'HR-V', year: 2022, plate: 'BCD-9H78' },
        { brand: 'Jeep', model: 'Compass', year: 2023, plate: 'IJK-2A89' },
        { brand: 'Ford', model: 'EcoSport', year: 2022, plate: 'LMN-5B90' },
        { brand: 'Volkswagen', model: 'Polo', year: 2022, plate: 'QRS-8C01' },
        { brand: 'Fiat', model: 'Toro', year: 2023, plate: 'UVW-3D12' },
        { brand: 'Toyota', model: 'Hilux', year: 2021, plate: 'XYZ-7E23' },
        { brand: 'Chevrolet', model: 'S10', year: 2022, plate: 'ABC-1F34' },
        { brand: 'Renault', model: 'Duster', year: 2021, plate: 'LMN-9G45' },
        { brand: 'Citroen', model: 'C4 Cactus', year: 2020, plate: 'OPQ-8H56' },
        { brand: 'Hyundai', model: 'Creta', year: 2021, plate: 'RST-6I67' },
        { brand: 'Peugeot', model: '3008', year: 2023, plate: 'VWX-4J78' },
        { brand: 'Jeep', model: 'Renegade', year: 2021, plate: 'XYZ-5A89' },
        { brand: 'Fiat', model: 'Bravo', year: 2021, plate: 'GHI-2B90' },
        { brand: 'Hyundai', model: 'HB20', year: 2021, plate: 'ABC-4C01' },
        { brand: 'Toyota', model: 'Etios', year: 2021, plate: 'DEF-3D12' },
        { brand: 'Chevrolet', model: 'Onix', year: 2022, plate: 'QRS-1E23' },
        { brand: 'Nissan', model: 'Kicks', year: 2023, plate: 'STU-6F34' },
        { brand: 'Mazda', model: 'CX-5', year: 2023, plate: 'OPQ-2G45' },
        { brand: 'Peugeot', model: '208', year: 2021, plate: 'LMN-7H56' },
        { brand: 'Renault', model: 'Captur', year: 2022, plate: 'XYZ-9I67' },
        { brand: 'Ford', model: 'Mustang', year: 2022, plate: 'PQR-4J78' },
        { brand: 'Volkswagen', model: 'Tiguan', year: 2023, plate: 'DEF-3A89' },
        { brand: 'Fiat', model: 'Punto', year: 2021, plate: 'UVW-2B90' },
        { brand: 'BMW', model: 'X1', year: 2023, plate: 'RST-7C01' },
        { brand: 'Mercedes', model: 'CLA', year: 2023, plate: 'QRS-6D12' },
        { brand: 'Honda', model: 'Fit', year: 2022, plate: 'TUV-4E23' },
        { brand: 'Chevrolet', model: 'Tracker', year: 2021, plate: 'ABC-5F34' },
        { brand: 'Toyota', model: 'Yaris', year: 2021, plate: 'EFG-1G45' },
        { brand: 'Hyundai', model: 'Sonata', year: 2023, plate: 'VWX-2H56' },
        { brand: 'Jeep', model: 'Grand Cherokee', year: 2021, plate: 'LMN-6I67' },
        { brand: 'Peugeot', model: '3008', year: 2022, plate: 'JKL-7J78' },
        { brand: 'Fiat', model: 'Panda', year: 2020, plate: 'RST-9A89' },
        { brand: 'Chery', model: 'Arrizo', year: 2022, plate: 'PQR-8B90' },
        { brand: 'Mazda', model: 'Miata', year: 2024, plate: 'BBC-7911' }
    ])
}