const db = require ('../src/database')

exports.seed = async (knex) => {
    await db('cars_items').insert([
        { name: "Ar condicionado", car_id: 5 },
        { name: "Vidro Eletrico", car_id: 5 },
        { name: "Sensor de estacionamento", car_id: 5 },
        { name: "Trava Eletrica", car_id: 10 },
        { name: "Banco de couro", car_id: 10 },
        { name: "Piloto automático", car_id: 10 },
        { name: "Vidro Eletrico", car_id: 15 },
        { name: "Roda de liga leve", car_id: 15 },
        { name: "Bluetooth", car_id: 15 },
        { name: "Roda de liga leve", car_id: 3 },
        { name: "Faróis de neblina", car_id: 3 },
        { name: "Alarme", car_id: 7 },
        { name: "Sistema de navegação", car_id: 7 },
        { name: "Câmbio automático", car_id: 7 },
        { name: "Airbag", car_id: 12 },
        { name: "Assistente de estacionamento", car_id: 12 },
        { name: "Câmbio automático", car_id: 19 },
        { name: "Banco de couro", car_id: 19 },
        { name: "Retrovisor elétrico", car_id: 19 },
        { name: "Sistema de navegação", car_id: 25 },
        { name: "Faróis de neblina", car_id: 25 },
        { name: "Controle de estabilidade", car_id: 25 },
        { name: "Faróis de neblina", car_id: 8 },
        { name: "Sensor de estacionamento", car_id: 8 },
        { name: "Sensor de estacionamento", car_id: 30 },
        { name: "Câmera de ré", car_id: 30 },
        { name: "Sistema de áudio premium", car_id: 30 },
        { name: "Banco de couro", car_id: 16 },
        { name: "Vidro Eletrico", car_id: 16 },
        { name: "Teto solar", car_id: 16 },
        { name: "Multimídia", car_id: 2 },
        { name: "Câmera de ré", car_id: 2 },
        { name: "Piloto automático", car_id: 2 },
        { name: "Suspensão a ar", car_id: 50 },
        { name: "Retrovisor elétrico", car_id: 50 },
        { name: "Aquecimento de banco", car_id: 50 },
        { name: "Rádio AM/FM", car_id: 45 },
        { name: "Bluetooth", car_id: 45 },
        { name: "Controle de estabilidade", car_id: 45 },
        { name: "Controle de tração", car_id: 45 },
        { name: "Vidro antiesmagamento", car_id: 33 },
        { name: "Ar condicionado", car_id: 33 },
        { name: "Trava Eletrica", car_id: 33 },
        { name: "Vidro Eletrico", car_id: 24 },
        { name: "Roda de liga leve", car_id: 24 },
        { name: "Alarme", car_id: 37 },
        { name: "Airbag", car_id: 37 },
        { name: "Câmbio automático", car_id: 37 },
        { name: "Sistema de navegação", car_id: 37 },
        { name: "Faróis de neblina", car_id: 23 },
        { name: "Sensor de estacionamento", car_id: 23 },
        { name: "Banco de couro", car_id: 34 },
        { name: "Teto solar", car_id: 34 },
        { name: "Multimídia", car_id: 34 },
        { name: "Assistente de estacionamento", car_id: 34 },
        { name: "Câmera de ré", car_id: 34 },
        { name: "Piloto automático", car_id: 34 },
        { name: "Suspensão a ar", car_id: 34 },
        { name: "Retrovisor elétrico", car_id: 34 },
        { name: "Aquecimento de banco", car_id: 34 },
        { name: "Rádio AM/FM", car_id: 34 },
        { name: "Bluetooth", car_id: 34 },
        { name: "Controle de estabilidade", car_id: 34 },
        { name: "Controle de tração", car_id: 34 },
        { name: "Vidro antiesmagamento", car_id: 34 }
    ])
}